language: php
php:
- 5.6.12
install:
- travis_retry composer install --no-interaction --prefer-dist --no-suggest
- cp .env.travis .env
- php artisan key:generate
sudo: false
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS laravelangular;'
before_script:
- phantomjs --webdriver=127.0.0.1:9515 &
- php artisan serve --port=8081 &
- sleep 5
services: mysql
script: php artisan dusk
